# Generated by Django 4.0.3 on 2022-06-14 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50, verbose_name='person_name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('sex', models.CharField(choices=[('MEN', 'men'), ('WOMEN', 'women')], max_length=10, verbose_name='sex')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Propertys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50, verbose_name='property_name')),
                ('image', models.ImageField(blank=True, upload_to='property/%y/$m//$d/')),
                ('is_fine', models.BooleanField(default=True)),
                ('taken_by_owner', models.BooleanField(default=False)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущества',
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='passport_number')),
                ('person_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Паспорт',
                'verbose_name_plural': 'Паспорта',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.propertys')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date'],
            },
        ),
    ]
