# Generated by Django 4.0.3 on 2022-06-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertys',
            old_name='is_fine',
            new_name='fine_is_paid',
        ),
        migrations.AlterField(
            model_name='propertys',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/%y/$m//$d/'),
        ),
    ]
