# Generated by Django 4.0.3 on 2022-06-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_propertys_fine_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertys',
            name='fine_is_paid',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertys',
            name='taken_by_owner',
            field=models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='no', max_length=10),
        ),
    ]
