# Generated by Django 4.0.3 on 2022-06-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_propertys_fine_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertys',
            name='fine_is_paid',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='propertys',
            name='taken_by_owner',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=10),
        ),
    ]
