# Generated by Django 4.0.3 on 2022-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_propertys_fine_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='number',
            field=models.CharField(max_length=50, verbose_name='номер документа'),
        ),
    ]
