# Generated by Django 4.0.3 on 2022-06-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertys',
            name='fine_is_paid',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertys',
            name='taken_by_owner',
            field=models.CharField(choices=[('NO', 'no'), ('YES', 'yes')], max_length=10),
        ),
    ]
