# Generated by Django 3.2.9 on 2021-11-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_alter_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='animal_category',
            field=models.CharField(choices=[('кошки', 'CAT'), ('собаки', 'DOG'), ('птицы', 'BIRDTS'), ('земноводные', 'AMPHIBIANS'), ('иное', 'OTHERS')], max_length=50, verbose_name='категория животного'),
        ),
    ]
