# Generated by Django 3.2.9 on 2021-11-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_alter_note_animal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='animal_category',
            field=models.CharField(choices=[('кошки', 'КОШКИ'), ('собаки', 'СОБАКИ'), ('птицы', 'ПТИЦЫ'), ('земноводные', 'ЗЕМНОВОДНЫЕ'), ('иное', 'ИНОЕ')], max_length=50, verbose_name='категория животного'),
        ),
    ]
