# Generated by Django 3.2.9 on 2021-11-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_note_animal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='info',
            field=models.TextField(max_length=1000, verbose_name='Текст заметки'),
        ),
    ]
