# Generated by Django 3.2.9 on 2022-01-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_announcement_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteuser',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noteuser',
            name='user_region',
            field=models.CharField(choices=[('BRO', 'Брестская область'), ('VIO', 'Витебская область'), ('GOO', 'Гомельская область'), ('GRO', 'Гродненская область'), ('MIO', 'Минская область'), ('MOO', 'Могилевская область'), ('MNSK', 'Минск')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
