# Generated by Django 3.2.9 on 2021-11-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_note_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='animal_category',
            field=models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog'), ('BIRD', 'bird'), ('AMPHIBIAN', 'amphibian'), ('OTHER', 'other')], max_length=50, verbose_name='категория животного'),
        ),
    ]
