# Generated by Django 3.2.9 on 2022-01-14 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_auto_20220111_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 15, 0, 37, 1, 573797), verbose_name='date of publication'),
        ),
    ]
