# Generated by Django 3.2.9 on 2021-11-29 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0008_alter_note_animal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.CharField(max_length=50, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=200, verbose_name='info of comment'),
        ),
        migrations.AlterField(
            model_name='note',
            name='animal_category',
            field=models.CharField(choices=[('CAT', 'cat'), ('DOG', 'dog'), ('BIRD', 'bird'), ('AMPHIBIAN', 'amphibian'), ('OTHER', 'other')], max_length=50, verbose_name='animal category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(verbose_name='date of publication'),
        ),
        migrations.AlterField(
            model_name='note',
            name='info',
            field=models.TextField(max_length=1000, verbose_name='Info of note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='place_of_find',
            field=models.CharField(max_length=50, verbose_name='place of find'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='name of author'),
        ),
    ]
