# Generated by Django 3.2.9 on 2021-12-01 21:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20211129_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 21, 35, 36, 34104, tzinfo=utc), verbose_name='date of publication'),
        ),
    ]
