# Generated by Django 3.2.9 on 2022-01-14 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_announcement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of publication'),
        ),
    ]
