# Generated by Django 3.2.9 on 2021-11-27 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_category', models.CharField(choices=[('cat', 'CAT'), ('cat', 'DOG'), ('birds', 'BIRDTS'), ('amphibians', 'AMPHIBIANS'), ('others', 'OTHERS')], max_length=50, verbose_name='категория животного')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('place_of_find', models.CharField(max_length=50, verbose_name='место найденного животного')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('info', models.TextField(max_length=200, verbose_name='Текст заметки')),
                ('data', models.DateTimeField(verbose_name='дата публикации заметки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='имя автора')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='комментатор')),
                ('text', models.CharField(max_length=200, verbose_name='текст коммента')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='animals.note')),
            ],
        ),
    ]
