# Generated by Django 3.2.9 on 2021-11-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='animal_category',
            field=models.CharField(choices=[('cat', 'CAT'), ('dog', 'DOG'), ('birds', 'BIRDTS'), ('amphibians', 'AMPHIBIANS'), ('others', 'OTHERS')], max_length=50, verbose_name='категория животного'),
        ),
        migrations.AlterField(
            model_name='note',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/animals/images/'),
        ),
    ]
