# Generated by Django 4.0.3 on 2022-04-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('М', 'м'), ('Ж', 'ж')], max_length=20),
        ),
    ]
