# Generated by Django 4.0.3 on 2022-06-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_customuser_gender_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MEN', 'Men'), ('WOMEN', 'Women')], max_length=20, null=True),
        ),
    ]
